name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rust:1.93.1

    steps:
    - uses: actions/checkout@v4

    - name: Cache Cargo bin
      uses: actions/cache@v4
      with:
        path: /usr/local/cargo/bin
        key: cargo-bin-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: cargo-bin-
    
    - name: Cache target
      uses: actions/cache@v4
      with:
        path: target
        key: target-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: target-

    - name: Report Toolchain Info
      run: |
        rustc --version
        cargo --version
        rustup show

    - name: Report OS-Release Info
      run: cat /etc/os-release

    - name: Report Shell Info
      run: echo $SHELL

    - name: Add wasm32-unknown-unknown compilation target
      run: rustup target add wasm32-unknown-unknown

    - name: Install Trunk
      run: |
        ls -lR ${{ env.CARGO_HOME }}/bin
        if ! command -v trunk >/dev/null; then
          cargo install trunk --version 0.21.14
        fi
        which trunk
        ls -ltR ~

    - name: Build (with trunk)
      run: trunk build --public-url /${{ github.event.repository.name }}/

    - name: Report build contents
      run: ls -lR dist

  deploy:
    runs-on: ubuntu-latest
    needs: build

    env:
      PROJECT_NAME: cli-mode-website

    steps:

    - uses: actions/checkout@v4

    - name: Create project (if missing)
      run: npx wrangler pages project create "$PROJECT_NAME" --production-branch main || echo "Project may already exist"
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

    - name: Build & Deploy Worker
      uses: cloudflare/wrangler-action@v3
      with:
        wranglerVersion: "4.69.0"
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        command: pages deploy dist --project-name="$PROJECT_NAME"
